name: Skip trigger

on: [push]

jobs:
  job1:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi 1
        run: echo "Hello from job1"
        
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi 2
        run: echo "Hello from job1"
