name: Skip trigger

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        if: github.event_name == 'push'
        run: echo "Hello from job1 on push"
      - name: Step 2
        if: github.event_name == 'release'
        run: echo "Hello from job1 on release"
        
      
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Say Hi 2
        run: echo "Hello from job1"
