name: Set env var

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print var
        run: echo $AGENT_TOOLSDIRECTORY
      - name: Set 
        run: |
          export FOOBAR=42
          echo $FOOBAR
      - name: Retrieve
        run: echo $FOOBAR
